/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokedam;

import javax.sound.sampled.*;
import java.io.File;

/**
 *
 * @author rikid
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SALIR = new javax.swing.JButton();
        Isaias = new javax.swing.JButton();
        Carolina = new javax.swing.JButton();
        Juan = new javax.swing.JButton();
        texto = new javax.swing.JTextArea();
        Luisa = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALIR.setBackground(new java.awt.Color(255, 51, 51));
        SALIR.setForeground(new java.awt.Color(255, 255, 255));
        SALIR.setText("SALIR");
        SALIR.setBorder(new javax.swing.border.MatteBorder(null));
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(SALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 130, 50));

        Isaias.setBackground(new java.awt.Color(255, 255, 0));
        Isaias.setText("ISAIAS");
        Isaias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsaiasActionperformed(evt);
            }
        });
        getContentPane().add(Isaias, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, -1, -1));

        Carolina.setBackground(new java.awt.Color(255, 51, 0));
        Carolina.setText("CAROLINA");
        Carolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarolinaActionPerformed(evt);
            }
        });
        getContentPane().add(Carolina, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, -1, -1));

        Juan.setBackground(new java.awt.Color(0, 255, 51));
        Juan.setText("JUAN");
        Juan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuanActionPerformed(evt);
            }
        });
        getContentPane().add(Juan, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, -1, -1));

        texto.setColumns(12);
        texto.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        texto.setForeground(new java.awt.Color(0, 0, 0));
        texto.setRows(5);
        texto.setOpaque(false);
        getContentPane().add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 390, 230));

        Luisa.setBackground(new java.awt.Color(153, 0, 153));
        Luisa.setText("LUISA");
        Luisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LuisaActionPerformed(evt);
            }
        });
        getContentPane().add(Luisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 570, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo2.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, -1));
        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 480, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SALIRActionPerformed

    private void IsaiasActionperformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsaiasActionperformed
        Menu m = new Menu();
        m.menu(texto,1);// devuelvo el argumento del label del texto ( en diseño)
        
    }//GEN-LAST:event_IsaiasActionperformed

    private void CarolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarolinaActionPerformed
         Menu m = new Menu();
        m.menu(texto,4);
    }//GEN-LAST:event_CarolinaActionPerformed

    private void JuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuanActionPerformed
        Menu m = new Menu();
        m.menu(texto,3);
    }//GEN-LAST:event_JuanActionPerformed

    private void LuisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LuisaActionPerformed
        Menu m = new Menu();
        m.menu(texto,2);
    }//GEN-LAST:event_LuisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
           
             Menu m = new Menu();
             m.menu(texto,5);
              try {
      // Crea un objeto File con la ruta del archivo de audio
      File audioFile = new File("C:\\Users\\rikid\\OneDrive\\Documentos\\NetBeansProjects\\InterfacesJava\\src\\pokemon.WAV");
      // Obtiene un flujo de audio a partir del archivo
      AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
      // Obtiene los datos del flujo de audio
      AudioFormat format = audioStream.getFormat();
      // Crea un clip de audio a partir de los datos del flujo
      DataLine.Info info = new DataLine.Info(Clip.class, format);
      Clip audioClip = (Clip) AudioSystem.getLine(info);
      audioClip.open(audioStream);
      // Reproduce el clip
      audioClip.start();
    } catch (Exception e) {
      e.printStackTrace();
    }
            
            
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carolina;
    private javax.swing.JButton Isaias;
    private javax.swing.JButton Juan;
    private javax.swing.JButton Luisa;
    private javax.swing.JButton SALIR;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
